### ISSUE TITLE
Enable Stale bot on adoptium-support repo

### ISSUE THREAD

**Issue by gdams** [adoptium/adoptium#141]
I'd like to propose that we enable [actions/stale](https://github.com/actions/stale) on the adoptium-support repo. It will allow us to close out issues that have not had a response from users.

Proposed config

```yml
name: "Close stale issues"
on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is stale because it has been open many days with no activity. It will be closed soon unless the stale label is removed or a comment is made.'
        stale-issue-label: 'stale'
        exempt-issue-labels: 'jbs:needs-report'
        days-before-stale: 90
        days-before-close: 30
        remove-stale-when-updated: true
```
